'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5485
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


Partial Public Class WineDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New(ByVal connection As String)
        MyBase.New(connection, mappingSource)
        Me.CommandTimeout = 0
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
        MyBase.New(connection, mappingSource)
        Me.CommandTimeout = 0
        OnCreated()
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
        MyBase.New(connection, mappingSource)
        Me.CommandTimeout = 0
        OnCreated()
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
        MyBase.New(connection, mappingSource)
        Me.CommandTimeout = 0
        OnCreated()
	End Sub
End Class



'<Table(Name:="dbo.tbBdgVino")> _
'Partial Public Class Vino
'    'Private _IDVino As System.Guid

'    'Private _Fecha As Date

'    'Private _IDDeposito As String

'    'Private _IDEstadoVino As String

'    'Private _Origen As Integer

'    'Private _TipoDeposito As Integer

'    'Private _IDArticulo As String

'    'Private _NOperacion As String

'    'Private _Ficticio As Boolean

'    'Private _Grupo As Boolean

'    'Private _IDUdMedida As String

'    'Private _CosteVariable As Decimal

'    'Private _CosteFiscal As Decimal

'    'Private _CosteTotal As Decimal

'    'Private _Lote As String

'    'Private _IDAlmacen As String

'    'Private _IDBarrica As String

'    'Private _DiasDeposito As Integer

'    'Private _DiasBarrica As Integer

'    'Private _DiasBotellero As Integer

'    'Private _QTotal As Double

'    'Private _CosteUnitarioInicialA As Decimal

'    'Private _FechaCosteUnitarioInicial As System.Nullable(Of Date)

'    '<Column(Storage:="_IDVino", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=True)> _
'    'Public Property IDVino() As System.Guid
'    '    Get
'    '        Return Me._IDVino
'    '    End Get
'    '    Set(ByVal value As System.Guid)
'    '        If ((Me._IDVino = value) _
'    '           = False) Then
'    '            Me._IDVino = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Fecha", DbType:="DateTime NOT NULL")> _
'    'Public Property Fecha() As Date
'    '    Get
'    '        Return Me._Fecha
'    '    End Get
'    '    Set(ByVal value As Date)
'    '        If ((Me._Fecha = value) _
'    '           = False) Then
'    '            Me._Fecha = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_IDDeposito", DbType:="NVarChar(25) NOT NULL", CanBeNull:=False)> _
'    'Public Property IDDeposito() As String
'    '    Get
'    '        Return Me._IDDeposito
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._IDDeposito, value) = False) Then
'    '            Me._IDDeposito = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_IDEstadoVino", DbType:="NVarChar(10)")> _
'    'Public Property IDEstadoVino() As String
'    '    Get
'    '        Return Me._IDEstadoVino
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._IDEstadoVino, value) = False) Then
'    '            Me._IDEstadoVino = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Origen", DbType:="Int NOT NULL")> _
'    'Public Property Origen() As Integer
'    '    Get
'    '        Return Me._Origen
'    '    End Get
'    '    Set(ByVal value As Integer)
'    '        If ((Me._Origen = value) _
'    '           = False) Then
'    '            Me._Origen = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_TipoDeposito", DbType:="Int NOT NULL")> _
'    'Public Property TipoDeposito() As Integer
'    '    Get
'    '        Return Me._TipoDeposito
'    '    End Get
'    '    Set(ByVal value As Integer)
'    '        If ((Me._TipoDeposito = value) _
'    '           = False) Then
'    '            Me._TipoDeposito = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_IDArticulo", DbType:="NVarChar(25) NOT NULL", CanBeNull:=False)> _
'    'Public Property IDArticulo() As String
'    '    Get
'    '        Return Me._IDArticulo
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._IDArticulo, value) = False) Then
'    '            Me._IDArticulo = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_NOperacion", DbType:="NVarChar(10)")> _
'    'Public Property NOperacion() As String
'    '    Get
'    '        Return Me._NOperacion
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._NOperacion, value) = False) Then
'    '            Me._NOperacion = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Ficticio", DbType:="Bit NOT NULL")> _
'    'Public Property Ficticio() As Boolean
'    '    Get
'    '        Return Me._Ficticio
'    '    End Get
'    '    Set(ByVal value As Boolean)
'    '        If ((Me._Ficticio = value) _
'    '           = False) Then
'    '            Me._Ficticio = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Grupo", DbType:="Bit NOT NULL")> _
'    'Public Property Grupo() As Boolean
'    '    Get
'    '        Return Me._Grupo
'    '    End Get
'    '    Set(ByVal value As Boolean)
'    '        If ((Me._Grupo = value) _
'    '           = False) Then
'    '            Me._Grupo = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_IDUdMedida", DbType:="NVarChar(10) NOT NULL", CanBeNull:=False)> _
'    'Public Property IDUdMedida() As String
'    '    Get
'    '        Return Me._IDUdMedida
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._IDUdMedida, value) = False) Then
'    '            Me._IDUdMedida = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_CosteVariable", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property CosteVariable() As Decimal
'    '    Get
'    '        Return Me._CosteVariable
'    '    End Get
'    '    Set(ByVal value As Decimal)
'    '        If ((Me._CosteVariable = value) _
'    '           = False) Then
'    '            Me._CosteVariable = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_CosteFiscal", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property CosteFiscal() As Decimal
'    '    Get
'    '        Return Me._CosteFiscal
'    '    End Get
'    '    Set(ByVal value As Decimal)
'    '        If ((Me._CosteFiscal = value) _
'    '           = False) Then
'    '            Me._CosteFiscal = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_CosteTotal", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property CosteTotal() As Decimal
'    '    Get
'    '        Return Me._CosteTotal
'    '    End Get
'    '    Set(ByVal value As Decimal)
'    '        If ((Me._CosteTotal = value) _
'    '           = False) Then
'    '            Me._CosteTotal = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Lote", DbType:="NVarChar(25) NOT NULL", CanBeNull:=False)> _
'    'Public Property Lote() As String
'    '    Get
'    '        Return Me._Lote
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._Lote, value) = False) Then
'    '            Me._Lote = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_IDAlmacen", DbType:="NVarChar(10) NOT NULL", CanBeNull:=False)> _
'    'Public Property IDAlmacen() As String
'    '    Get
'    '        Return Me._IDAlmacen
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._IDAlmacen, value) = False) Then
'    '            Me._IDAlmacen = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_IDBarrica", DbType:="NVarChar(10)")> _
'    'Public Property IDBarrica() As String
'    '    Get
'    '        Return Me._IDBarrica
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._IDBarrica, value) = False) Then
'    '            Me._IDBarrica = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_DiasDeposito", DbType:="Int NOT NULL")> _
'    'Public Property DiasDeposito() As Integer
'    '    Get
'    '        Return Me._DiasDeposito
'    '    End Get
'    '    Set(ByVal value As Integer)
'    '        If ((Me._DiasDeposito = value) _
'    '           = False) Then
'    '            Me._DiasDeposito = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_DiasBarrica", DbType:="Int NOT NULL")> _
'    'Public Property DiasBarrica() As Integer
'    '    Get
'    '        Return Me._DiasBarrica
'    '    End Get
'    '    Set(ByVal value As Integer)
'    '        If ((Me._DiasBarrica = value) _
'    '           = False) Then
'    '            Me._DiasBarrica = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_DiasBotellero", DbType:="Int NOT NULL")> _
'    'Public Property DiasBotellero() As Integer
'    '    Get
'    '        Return Me._DiasBotellero
'    '    End Get
'    '    Set(ByVal value As Integer)
'    '        If ((Me._DiasBotellero = value) _
'    '           = False) Then
'    '            Me._DiasBotellero = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_QTotal", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property QTotal() As Double
'    '    Get
'    '        Return Me._QTotal
'    '    End Get
'    '    Set(ByVal value As Double)
'    '        If ((Me._QTotal = value) _
'    '           = False) Then
'    '            Me._QTotal = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_CosteUnitarioInicialA", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property CosteUnitarioInicialA() As Decimal
'    '    Get
'    '        Return Me._CosteUnitarioInicialA
'    '    End Get
'    '    Set(ByVal value As Decimal)
'    '        If ((Me._CosteUnitarioInicialA = value) _
'    '           = False) Then
'    '            Me._CosteUnitarioInicialA = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_FechaCosteUnitarioInicial", DbType:="DateTime")> _
'    'Public Property FechaCosteUnitarioInicial() As System.Nullable(Of Date)
'    '    Get
'    '        Return Me._FechaCosteUnitarioInicial
'    '    End Get
'    '    Set(ByVal value As System.Nullable(Of Date))
'    '        If (Me._FechaCosteUnitarioInicial.Equals(value) = False) Then
'    '            Me._FechaCosteUnitarioInicial = value
'    '        End If
'    '    End Set
'    'End Property

'End Class

'<Table(Name:="dbo.tbBdgVinoEstructura")> _
'Public Class VinoEstructura

'    'Private _IDVino As System.Guid

'    'Private _IDVinoComponente As System.Guid

'    'Private _Cantidad As Double

'    'Private _Merma As Double

'    'Private _Factor As Double

'    'Private _Operacion As String

'    'Private _NOperacion As String

'    '<Column(Storage:="_IDVino", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=True)> _
'    'Public Property IDVino() As System.Guid
'    '    Get
'    '        Return Me._IDVino
'    '    End Get
'    '    Set(ByVal value As System.Guid)
'    '        If ((Me._IDVino = value) _
'    '           = False) Then
'    '            Me._IDVino = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_IDVinoComponente", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=True)> _
'    'Public Property IDVinoComponente() As System.Guid
'    '    Get
'    '        Return Me._IDVinoComponente
'    '    End Get
'    '    Set(ByVal value As System.Guid)
'    '        If ((Me._IDVinoComponente = value) _
'    '           = False) Then
'    '            Me._IDVinoComponente = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Cantidad", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property Cantidad() As Double
'    '    Get
'    '        Return Me._Cantidad
'    '    End Get
'    '    Set(ByVal value As Double)
'    '        If ((Me._Cantidad = value) _
'    '           = False) Then
'    '            Me._Cantidad = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Merma", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property Merma() As Double
'    '    Get
'    '        Return Me._Merma
'    '    End Get
'    '    Set(ByVal value As Double)
'    '        If ((Me._Merma = value) _
'    '           = False) Then
'    '            Me._Merma = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Factor", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property Factor() As Double
'    '    Get
'    '        Return Me._Factor
'    '    End Get
'    '    Set(ByVal value As Double)
'    '        If ((Me._Factor = value) _
'    '           = False) Then
'    '            Me._Factor = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Operacion", DbType:="NVarChar(10) NOT NULL", CanBeNull:=False, IsPrimaryKey:=True)> _
'    'Public Property Operacion() As String
'    '    Get
'    '        Return Me._Operacion
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._Operacion, value) = False) Then
'    '            Me._Operacion = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_NOperacion", DbType:="NVarChar(10)")> _
'    'Public Property NOperacion() As String
'    '    Get
'    '        Return Me._NOperacion
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._NOperacion, value) = False) Then
'    '            Me._NOperacion = value
'    '        End If
'    '    End Set
'    'End Property


'End Class

'<Table(Name:="dbo.tbBdgDepositoVino")> _
'Public Class DepositoVino

'    'Private _IDVino As System.Guid

'    'Private _IDDeposito As String

'    'Private _Cantidad As Decimal

'    '<Column(Storage:="_IDVino", DbType:="UniqueIdentifier NOT NULL", IsPrimaryKey:=True)> _
'    'Public Property IDVino() As System.Guid
'    '    Get
'    '        Return Me._IDVino
'    '    End Get
'    '    Set(ByVal value As System.Guid)
'    '        If ((Me._IDVino = value) _
'    '           = False) Then
'    '            Me._IDVino = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_IDDeposito", DbType:="NVarChar(25) NOT NULL", CanBeNull:=False)> _
'    'Public Property IDDeposito() As String
'    '    Get
'    '        Return Me._IDDeposito
'    '    End Get
'    '    Set(ByVal value As String)
'    '        If (String.Equals(Me._IDDeposito, value) = False) Then
'    '            Me._IDDeposito = value
'    '        End If
'    '    End Set
'    'End Property

'    '<Column(Storage:="_Cantidad", DbType:="Decimal(23,8) NOT NULL")> _
'    'Public Property Cantidad() As Decimal
'    '    Get
'    '        Return Me._Cantidad
'    '    End Get
'    '    Set(ByVal value As Decimal)
'    '        If ((Me._Cantidad = value) _
'    '           = False) Then
'    '            Me._Cantidad = value
'    '        End If
'    '    End Set
'    'End Property

'End Class

